/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EmojiRouteImport } from './routes/emoji'
import { Route as MemoRouteImport } from './routes/memo'
import { Route as MyshadowRouteImport } from './routes/myshadow'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EmojiRoute = EmojiRouteImport.update({
  id: '/emoji',
  path: '/emoji',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoRoute = MemoRouteImport.update({
  id: '/memo',
  path: '/memo',
  getParentRoute: () => rootRouteImport,
} as any)
const MyshadowRoute = MyshadowRouteImport.update({
  id: '/myshadow',
  path: '/myshadow',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emoji': typeof EmojiRoute
  '/memo': typeof MemoRoute
  '/myshadow': typeof MyshadowRoute
  '/reading': typeof ReadingRoute
  '/writing': typeof WritingRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emoji': typeof EmojiRoute
  '/memo': typeof MemoRoute
  '/myshadow': typeof MyshadowRoute
  '/reading': typeof ReadingRoute
  '/writing': typeof WritingRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/emoji': typeof EmojiRoute
  '/memo': typeof MemoRoute
  '/myshadow': typeof MyshadowRoute
  '/reading': typeof ReadingRoute
  '/writing': typeof WritingRoute
  '/posts/$slug': typeof PostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/emoji'
    | '/memo'
    | '/myshadow'
    | '/reading'
    | '/writing'
    | '/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/emoji'
    | '/memo'
    | '/myshadow'
    | '/reading'
    | '/writing'
    | '/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/emoji'
    | '/memo'
    | '/myshadow'
    | '/reading'
    | '/writing'
    | '/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EmojiRoute: typeof EmojiRoute
  MemoRoute: typeof MemoRoute
  MyshadowRoute: typeof MyshadowRoute
  ReadingRoute: typeof ReadingRoute
  WritingRoute: typeof WritingRoute
  PostsSlugRoute: typeof PostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoji': {
      id: '/emoji'
      path: '/emoji'
      fullPath: '/emoji'
      preLoaderRoute: typeof EmojiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memo': {
      id: '/memo'
      path: '/memo'
      fullPath: '/memo'
      preLoaderRoute: typeof MemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myshadow': {
      id: '/myshadow'
      path: '/myshadow'
      fullPath: '/myshadow'
      preLoaderRoute: typeof MyshadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EmojiRoute: EmojiRoute,
  MemoRoute: MemoRoute,
  MyshadowRoute: MyshadowRoute,
  ReadingRoute: ReadingRoute,
  WritingRoute: WritingRoute,
  PostsSlugRoute: PostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
